### ISSUE TITLE
Add bachelors and masters thesis

### ISSUE THREAD

**Issue by SteffenGivard** [SteffenGivard/bjarkekingo.dk#2]
Maybe also would be nice to add [bachelors](https://github.com/Pjuske/Bachelors-Thesis) and [masters thesis](https://github.com/Pjuske/Masters-Thesis)?

_Originally posted by @Pjuske in https://github.com/SteffenGivard/bjarkekingo.dk/issues/1#issuecomment-769260359_

**Comment by Pjuske** [comment]
I would think simply as a link to the respective PDF-file
